#- name: Debug
#  debug:
#    msg: ls

- name: '步骤: 拷贝通用文件'
  include_role:
    name: 'files-copy'
- name: '步骤: 环境配置检测件'
  include_role:
    name: 'env-check'
- name: '步骤: 生成 rke k8s 配置'
  include_role:
    name: 'config'

- name: '步骤: 等待 rke2 server 可用'
  shell: curl -kSsL https://{{ rke2.server.url }}:9345/cacerts | grep 'BEGIN.*.CERTIFICATE' > /dev/null 2>&1; echo $?
  register: state_results
  until: state_results.stdout|int == 0
  delay: 6
  retries: 4000

- name: '步骤: 停止 rke2 agent'
  shell: 'systemctl stop rke2-agent.service;'
  when: inventory_hostname in groups['agent']

- name: '步骤: 拷贝 rke2 二进制文件到指定目录'
  shell: 'cp -rf /tmp/rke2 /usr/local/bin/rke2'
  when: inventory_hostname in groups['agent']

- name: '步骤: 重启 rke2 agent'
  shell: 'systemctl restart rke2-agent.service; systemctl enable rke2-agent.service'
  when: inventory_hostname in groups['agent']
