---
- name: '步骤: 停止 rke2 服务'
  shell: "{{ item }}"
  with_items:
    - systemctl stop rke2-server.service > /dev/null 2>&1; echo $?;
    - systemctl stop rke2-agent.service > /dev/null 2>&1; echo $?;
  tags: []
  when: hostvars[inventory_hostname].remove_node is defined and hostvars[inventory_hostname].remove_node|bool == true

- name: '步骤: 卸载 rke2'
  shell: "{{ item }}"
  with_items:
    - rke2-killall.sh > /dev/null 2>&1; echo $?;
    - rke2-uninstall.sh > /dev/null 2>&1; echo $?;
  tags: []
  when: hostvars[inventory_hostname].remove_node is defined and hostvars[inventory_hostname].remove_node|bool == true

- name: '步骤: 删除残留文件'
  shell: "{{ item }}"
  with_items:
    - rm -rf /var/lib/rancher/rke2/agent/client*
    - rm -rf /var/lib/rancher/rke2/agent/kubelet.kubeconfig
    - rm -rf /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig
    - rm -rf /var/lib/rancher/rke2/agent/logs/
    - rm -rf /var/lib/rancher/rke2/agent/pod-manifests/
    - rm -rf /var/lib/rancher/rke2/agent/server-ca.crt
    - rm -rf /var/lib/rancher/rke2/agent/rke2controller.kubeconfig
    - rm -rf /var/lib/rancher/rke2/agent/serving-kubelet.crt
    - rm -rf /var/lib/rancher/rke2/agent/serving-kubelet.key
    - rm -rf /var/lib/rancher/rke2/data
    - rm -rf /var/lib/rancher/rke2/server
    - rm -rf /var/lib/rancher/rke2/bin
  tags: []
  when: hostvars[inventory_hostname].remove_node is defined and hostvars[inventory_hostname].remove_node|bool == true

- name: "步骤: 从 rke2 k8s 集群中删除节点: {% for host in groups['all'] %}{% if hostvars[host]['remove_node'] is defined and hostvars[host]['remove_node']|bool == true %}{{ hostvars[host].node_name }}{% endif %}{% endfor %}"
  shell: /var/lib/rancher/rke2/bin/kubectl delete node {% for host in groups['all'] %}{% if hostvars[host]['remove_node'] is defined and hostvars[host]['remove_node']|bool == true %}{{ hostvars[host].node_name }}{% endif %}{% endfor %}
  when:  inventory_hostname in groups['init_master']
  tags: []
