---
- name: '任务: Gather_facts 获取主机信息'
  hosts: "all"

- name: '任务: Debug'
  hosts: "all"
  tasks:
  - debug: var=ansible_user
  tags: debug,never

- name: '任务: 拷贝通用文件'
  hosts: "all"
  gather_facts: false
  roles:
  - { role: 'files-copy', tags: 'files-copy', when: rke2.operation_type is defined and (rke2.operation_type == 'install' or rke2.operation_type == 'upgrade') }

- name: '任务: 环境检查'
  hosts: "all"
  gather_facts: false
  roles:
  - { role: 'env-check', tags: 'env-check', when: rke2.operation_type is defined and (rke2.operation_type == 'install' or rke2.operation_type == 'upgrade') }

- name: '任务: 生成或者更新配置'
  hosts: "all"
  gather_facts: false
  roles:
  - { role: 'config', tags: 'config', when: rke2.operation_type is defined and (rke2.operation_type == 'install' or rke2.operation_type == 'upgrade') }

# 安装 Init Master
- name: '任务: 安装/升级 Init Master'
  hosts: "init_master"
  serial: 1
  roles:
  - { role: 'init-master', tags: 'init-master', when: rke2.operation_type is defined and (rke2.operation_type == 'install' or rke2.operation_type == 'upgrade') }

# 安装/升级 Matser 节点
- name: '任务: 安装 Master'
  hosts: "master"
  gather_facts: false
  serial: 1
  roles:
  - { role: 'master', tags: 'master', when: rke2.operation_type is defined and rke2.operation_type == 'install' }

- name: '任务: 升级 Master'
  hosts: "master"
  gather_facts: false
  serial: 1
  roles:
  - { role: 'master', tags: 'master', when: rke2.operation_type is defined and rke2.operation_type == 'upgrade' }

# 安装/升级 Agent 节点
- name: '任务: 安装 Agent 节点'
  hosts: "agent"
  gather_facts: false
  roles:
  - { role: 'agent', tags: 'agent', when: rke2.operation_type is defined and rke2.operation_type == 'install' }

- name: '任务: 升级 Agent 节点'
  hosts: "agent"
  gather_facts: false
  serial: 1
  roles:
  - { role: 'agent', tags: 'agent', when: rke2.operation_type is defined and rke2.operation_type == 'upgrade' }

## 添加 Matser 节点
- name: '任务: 添加 Master'
  hosts: "master"
  gather_facts: false
  serial: 1
  roles:
  - { role: 'add-master-node', tags: 'add-master-node', when: rke2.operation_type is defined and rke2.operation_type == 'add-master-node' }

## 添加 Agent 节点
- name: '任务: 添加 Agent'
  hosts: "agent"
  gather_facts: false
  roles:
  - { role: 'add-agent-node', tags: 'add-agent-node', when: rke2.operation_type is defined and rke2.operation_type == 'add-agent-node' }

# 删除节点
- name: '任务: 删除节点'
  hosts: "all"
  gather_facts: false
  roles:
  - { role: 'remove-node', tags: 'remove-node', when: rke2.operation_type is defined and rke2.operation_type == 'remove-node' }

# 卸载
- name: '任务: 卸载集群'
  hosts: "all"
  gather_facts: false
  roles:
  - { role: 'uninstall', tags: 'uninstall', when: rke2.operation_type is defined and rke2.operation_type == 'uninstall' }