#- name: Debug
#  debug:
#    msg: ls
#
- name: '步骤: 拷贝通用文件'
  include_role:
    name: 'files-copy'
  when: init_server is undefined or init_server|bool != true

- name: '步骤: 环境配置检测件'
  include_role:
    name: 'env-check'
  when: init_server is undefined or init_server|bool != true

- name: '步骤: 生成 rke k8s 配置'
  include_role:
    name: 'config'
  when: init_server is undefined or init_server|bool != true

- name: '步骤: 等待 init server 安装完成'
  shell: curl -kSsL https://{{ rke2.server.url }}:9345/cacerts | grep 'BEGIN.*.CERTIFICATE' > /dev/null 2>&1; echo $?
  register: state_results
  until: state_results.stdout|int == 0
  delay: 6
  retries: 4000
  when: init_server is undefined or init_server|bool != true

- name: '步骤: 停止 rke2 server'
  shell: 'systemctl stop rke2-server.service;'
  when: init_server is undefined or init_server|bool != true

- name: '步骤: 拷贝 rke2 二进制文件到指定目录'
  shell: 'cp -rf /tmp/rke2 /usr/local/bin/rke2'
  when: init_server is undefined or init_server|bool != true

- name: '步骤: 重启 rke2 server'
  shell: 'systemctl restart rke2-server.service; systemctl enable rke2-server.service'
  when: init_server is undefined or init_server|bool != true

- name: '步骤: 等待 rke2 server 完成重启'
  shell: if [ "$(/var/lib/rancher/rke2/bin/kubectl get node > /dev/null 2>&1; echo $?)" = '0' ];then echo 0; fi
  register: result
  until: result.stdout == '0'
  delay: 6
  retries: 4000
  when: init_server is undefined or init_server|bool != true